apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-mesh
    type: influxdb
    access: proxy
    url: http://hub-influx:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      httpMode: POST
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
