using Engine.Packets;

namespace Engine.Devices;

/// <summary>
/// Represents the central hub (gateway) device of the simulation network.
/// The hub is the designated destination for packets generated by
/// <see cref="GeneratorDevice"/> instances and the root of the network topology.
/// It is registered as the singleton hub inside <see cref="Engine.Core.SimulationEngine"/>
/// when added to the simulation.
/// </summary>
public class HubDevice : Device
{
    /// <summary>
    /// Accepts a packet that has been delivered to the hub and logs it.
    /// </summary>
    /// <param name="packet">The delivered packet.</param>
    public override void Accept(Packet packet)
    {
        Log(packet);
    }

    private void Log(Packet packet)
    {
    }
}
